use bevy_ecs::prelude::Component;
use std::collections::HashMap;
use glam::{Vec2, Vec3};

#[derive(Component)]
pub struct Entity {
    pub position: Vec3,
    pub rotation: Vec2,
    pub velocity: Vec3,

    // NBT fields
    pub chested: bool,
    pub color: u8,
    pub color2: u8,
    pub custom_name: Option<String>,
    pub custom_name_visible: Option<bool>,
    pub definitions: Option<Vec<String>>,
    pub fall_distance: f32,
    pub fire: Option<i16>,
    pub identifier: String,
    pub internal_components: HashMap<String, HashMap<String, String>>,
    pub invulnerable: bool,
    pub is_angry: bool,
    pub is_autonomous: bool,
    pub is_baby: bool,
    pub is_eating: bool,
    pub is_gliding: bool,
    pub is_global: bool,
    pub is_illager_captain: bool,
    pub is_orphaned: bool,
    pub is_out_of_control: bool,
    pub is_roaring: bool,
    pub is_scared: bool,
    pub is_stunned: bool,
    pub is_swimming: bool,
    pub is_tamed: bool,
    pub is_trusting: bool,
    pub last_dimension_id: Option<i32>,
    pub links_tag: Option<HashMap<String, nbtx::Value>>,
    pub loot_dropped: bool,
    pub mark_variant: i32,
    // motion -> velocity
    pub on_ground: bool,
    pub owner_new: i64,
    pub persistent: bool,
    pub portal_cooldown: i32,
    // pos -> position
    // rotation -> rotation
    pub saddled: bool,
    pub sheared: bool,
    pub show_bottom: bool,
    pub sitting: bool,
    pub skin_id: i32,
    pub strength: i32,
    pub strength_max: i32,
    pub tags: Option<Vec<String>>,
    pub unique_id: i64,
    pub variant: i32,
}

impl Entity {
    pub fn default(identifier: String, unique_id: i64) -> Self {
        Self {
            position: Vec3::ZERO,
            rotation: Vec2::ZERO,
            velocity: Vec3::ZERO,
            chested: false,
            color: 0,
            color2: 0,
            custom_name: None,
            custom_name_visible: None,
            definitions: None,
            fall_distance: 0.0,
            fire: None,
            identifier,
            internal_components: HashMap::new(),
            invulnerable: false,
            is_angry: false,
            is_autonomous: false,
            is_baby: false,
            is_eating: false,
            is_gliding: false,
            is_global: false,
            is_illager_captain: false,
            is_orphaned: false,
            is_out_of_control: false,
            is_roaring: false,
            is_scared: false,
            is_stunned: false,
            is_swimming: false,
            is_tamed: false,
            is_trusting: false,
            last_dimension_id: None,
            links_tag: None,
            loot_dropped: false,
            mark_variant: 0,
            on_ground: false,
            owner_new: -1,
            persistent: false,
            portal_cooldown: 0,
            saddled: false,
            sheared: false,
            show_bottom: false,
            sitting: false,
            skin_id: 0,
            strength: 0,
            strength_max: 0,
            tags: None,
            unique_id,
            variant: 0,
        }
    }
}
