[package]
name = "rastra-server"
version.workspace = true
description = "Server project of RAstra"
edition = "2021"

[dependencies]
rastra-api = { path = "../rastra-api" }
rastra-utils = { path = "../rastra-utils" }
rastra-config = { path = "../rastra-config" }
tokio = { version = "1", features = ["full"] }

log = "0.4"
chrono = "0.4"

bedrockrs = { git = "https://github.com/bedrock-crustaceans/bedrockrs", branch = "main", features = ["full"] }
anyhow = "1.0.102"
uuid = { version = "1.22.0", features = ["v4"] }